name: NodeJS-CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: running SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            export PATH=$PATH:/root/.local/share/pnpm/pnpm
            export PATH=$PATH:/root/.local/share/pnpm/pm2
            source ~/.bashrc
            cd /usr/projects/test-express
            git pull origin main
            pnpm install
            pm2 restart 0
            
            # cd /usr/projects/test-express
            # git pull origin main
            # /root/.local/share/pnpm/pnpm install
            # /root/.local/share/pnpm/pm2 restart 0
